### PR TITLE
add tooltips for active flooding layers 184

### PR DESCRIPTION
**Pull request by lilyhoutman**
lauren/abby tell me how u think this looks (we can ask daniel too?)
lauren had said to include tooltips in the sidebar and legend. which when only one of them is open i think makes sense, but when they're both open i'm afraid it's overwhelming? what do u think
it could also maybe be less overwhelming if not a bright blue? i like the bright blue when it's just one of the two, i think it matches the theme and stands out (in fact, it makes me want to reconsider the grey tooltips in wqp to something brighter)
but perhaps if it were duller then having two would work?

### CODE REVIEW

**Comment by lprivette** [comment]
I like the bright blue too, but it seems a little too close to the blue flooding in the icon for some reason. Maybe changing the opacity slightly? 

I don't find the tooltips when open in both locations overwhelming. This would be a good question if we were doing tests with users. Could leave both in and ask the group on Thursday.

**Comment by lilyhoutman** [comment]
image
i made it slightly lighter. i think like you said we can go with this for now and see what users think!

**Comment by lprivette** [comment]
sounds good, can you add a note to the changelog?

**Comment by lilyhoutman** [comment]
done now! i need to put a sticky note on my computer that says "did u update the changelog" i think...

**Review by lprivette — APPROVED** [review]

**Pull request merged**
