### PR TITLE
55 change icons to circles

### PR DESCRIPTION
**Pull request by lilyhoutman**
-changed icons to circles
-removed other icons
-updated links to access circle icons

### CODE REVIEW

**Review by lprivette — APPROVED** [review]

**Comment by lprivette** [comment]
Oops can you add this change to the Changelog @lilyhoutman ?

**Comment by lilyhoutman** [comment]
> Oops can you add this change to the Changelog @lilyhoutman ?

whoops forgot that was a thing, done now

**Comment by lprivette** [comment]
image
It needs to go in the "Unreleased" section of the changelog. Unreleased means that it hasn't been deployed yet, so we'll add all our changes to that section and then when I tag and release it (like i did yesterday) I'll update that section in the changelog with links to the 'release' and make the unreleased section empty again. We want to give users an easy place to view what changes were made when we release a new version of the app.

Here's an example of a longer changelog https://github.com/USGS-WiM/stnweb2/blob/dev/CHANGELOG.md

**Comment by lilyhoutman** [comment]
> image
> It needs to go in the "Unreleased" section of the changelog. Unreleased means that it hasn't been deployed yet, so we'll add all our changes to that section and then when I tag and release it (like i did yesterday) I'll update that section in the changelog with links to the 'release' and make the unreleased section empty again. We want to give users an easy place to view what changes were made when we release a new version of the app.
> 
> Here's an example of a longer changelog https://github.com/USGS-WiM/stnweb2/blob/dev/CHANGELOG.md

sorry ok i haven't been on this project in so long i completely missed that section. fixed now i THINK

**Pull request merged**
