### PR TITLE
246 - display all threshold icons in sidebar and legend

### PR DESCRIPTION
**Pull request by Abigail770**
Let me know if this doesn't line up with what was discussed in the meeting.

I left in the "No active flooding" label in the sidebar when all icons are disabled, but I'm wondering if we should just keep the "Active Flooding Layers" title there now that any icons in the list without active flooding will be disabled:
image
activeflooding

### CODE REVIEW

**Comment by chaqazarad** [comment]
Not sure if it's there, but make sure there is appropriate disabled tool tip text. 
Also the information icons shouldn't be disabled, that means users would have to hunt for a day with flooding just to click on the icons.  (they look disabled from the image)

**Comment by lprivette** [comment]
What would be a good tooltip to put next to the "No Active Flooding" layer?

Something like: 

Layers disabled because no locations are currently flooding. 
OR
Select a date above to view flooding on past dates.
OR
both sentences?

**Comment by chaqazarad** [comment]
> What would be a good tooltip to put next to the "No Active Flooding" layer?
> 
> Something like:
> 
> Layers disabled because no locations are currently flooding. OR Select a date above to view flooding on past dates. OR both sentences?

I'm not a fan of disabling them at all. Another issue is I feel like we should be clear between "Active Flooding" and "Thresholds Exceeded" I think we have kind of been using the terms interchangeably, we should probably stick to one terminology to avoid confusion for users. 

If we are going to disable them, then maybe something like "[There is no active flooding | There are no exceeded thresholds] on this date. Select a different date.

**Comment by lprivette** [comment]
Yes per the last checkin we are no longer using the words "Thresholds" or "Reference Points" in favor of more generic language like "feature". Which is why the "All Reference Point" Layer is now, "All Features" . You shouldn't see either of those words on display to the user and if you do let us know. 

I added  the alert:
image

The argument for showing the layers as disabled was that the user wouldn't be aware of them at all on a typical day where there is no flooding. By seeing the disabled layers, they know that they are possible, which prompts them to change the date. I've added a tool tip to the "no active layers" text explaining that they are disabled because there is no flooding, and to select another date

**Review by lprivette — APPROVED** [review]

**Pull request merged**
